/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v3/auth/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create single-use browser-bound challenge (60 seconds). */
        post: operations["post__v3_auth_challenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/auth/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange pinned issuer assertion plus challenge cookie for fresh Go session. */
        post: operations["post__v3_auth_exchange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/auth/account-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Project signed version-advancing account state; consumes JTI and revokes existing sessions. */
        post: operations["post__v3_auth_account-state"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve current local session/account/site-role. */
        get: operations["get__v3_auth_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/auth/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** rotate with retained session records. Lost rotate response requires fresh login; old token is not replayed. */
        post: operations["post__v3_auth_rotate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** logout with retained session records. Lost rotate response requires fresh login; old token is not replayed. */
        post: operations["post__v3_auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/auth/revoke-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** revoke-all with retained session records. Lost rotate response requires fresh login; old token is not replayed. */
        post: operations["post__v3_auth_revoke-all"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/auth/site-role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Local site-admin-only versioned grant/demotion with last-local-admin guard. */
        post: operations["post__v3_auth_site-role"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Site admin creates independent Class. */
        post: operations["post__v3_classes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/classes/{class_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read authorized Class; Student cannot read DRAFT or suspended/ended membership. */
        get: operations["get__v3_classes_class_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Assigned Teacher or site admin edits Class using current version. */
        patch: operations["patch__v3_classes_class_id"];
        trace?: never;
    };
    "/v3/classes/{class_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish DRAFT with active unsuspended Teacher; content readiness remains M07 gate. */
        post: operations["post__v3_classes_class_id_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/classes/{class_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Site admin archive with state/version guard. CLOSED is read-only; ARCHIVED terminal. */
        post: operations["post__v3_classes_class_id_archive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/classes/{class_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Site admin close with state/version guard. CLOSED is read-only; ARCHIVED terminal. */
        post: operations["post__v3_classes_class_id_close"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/classes/{class_id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Site admin reopen with state/version guard. CLOSED is read-only; ARCHIVED terminal. */
        post: operations["post__v3_classes_class_id_reopen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/classes/{class_id}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin assigns Teacher/Student. Teacher assigns only Students and cannot modify existing staff targets. */
        post: operations["post__v3_classes_class_id_participants"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/classes/{class_id}/participants/{user_id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin or assigned Teacher end participation; Teacher cannot target staff. Last active Teacher protected on PUBLISHED Class. */
        post: operations["post__v3_classes_class_id_participants_user_id_end"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/classes/{class_id}/participants/{user_id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin or assigned Teacher suspend participation; Teacher cannot target staff. Last active Teacher protected on PUBLISHED Class. */
        post: operations["post__v3_classes_class_id_participants_user_id_suspend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/classes/{class_id}/participants/{user_id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin or assigned Teacher reactivate participation; Teacher cannot target staff. Last active Teacher protected on PUBLISHED Class. */
        post: operations["post__v3_classes_class_id_participants_user_id_reactivate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Empty: Record<string, never>;
        Assertion: {
            assertion: string;
        };
        Version: {
            version: number;
        };
        SiteRole: {
            user_id: string;
            admin: boolean;
            version: number;
        };
        CreateClass: {
            /** @description Non-blank; Go additionally enforces at most 200 UTF-8 bytes. */
            name: string;
            /** @description At most 200 UTF-8 bytes. */
            program_label?: string;
            /** @description At most 200 UTF-8 bytes. */
            cohort_label?: string;
        };
        EditClass: {
            /** @description Non-blank; Go additionally enforces at most 200 UTF-8 bytes. */
            name: string;
            /** @description At most 200 UTF-8 bytes. */
            program_label?: string;
            /** @description At most 200 UTF-8 bytes. */
            cohort_label?: string;
            version: number;
        };
        Participant: {
            user_id: string;
            /** @enum {string} */
            role: "teacher" | "student";
        };
        Class: {
            id?: string;
            name?: string;
            program_label?: string;
            cohort_label?: string;
            /** @enum {string} */
            state?: "DRAFT" | "PUBLISHED" | "CLOSED" | "ARCHIVED";
            version?: number;
        };
        Credential: {
            csrf_token: string;
        };
        Actor: {
            id?: string;
            site_admin?: boolean;
        };
        Challenge: {
            nonce?: string;
        };
        Status: {
            status?: string;
        };
        Participation: {
            class_id?: string;
            enrollment_id?: string;
            user_id?: string;
            role?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "SUSPENDED" | "ENDED";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post__v3_auth_challenge: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact configured HTTPS origin; no trust in forwarded origin. */
                Origin: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Empty"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Challenge"];
                };
            };
            /** @description Invalid JSON/input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid/expired session or assertion */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Capability, CSRF or origin denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource or owner-only route unavailable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description State/version/replay/invariant conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Process-local challenge limit reached (120/minute). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dependency unavailable; fail closed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post__v3_auth_exchange: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact configured HTTPS origin; no trust in forwarded origin. */
                Origin: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Assertion"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Credential"];
                };
            };
            /** @description Invalid JSON/input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid/expired session or assertion */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Capability, CSRF or origin denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource or owner-only route unavailable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description State/version/replay/invariant conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dependency unavailable; fail closed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "post__v3_auth_account-state": {
        parameters: {
            query?: never;
            header: {
                /** @description Exact configured HTTPS origin; no trust in forwarded origin. */
                Origin: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Assertion"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            /** @description Invalid JSON/input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid/expired session or assertion */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Capability, CSRF or origin denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource or owner-only route unavailable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description State/version/replay/invariant conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dependency unavailable; fail closed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get__v3_auth_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Actor"];
                };
            };
            /** @description Invalid JSON/input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid/expired session or assertion */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Capability, CSRF or origin denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource or owner-only route unavailable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description State/version/replay/invariant conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dependency unavailable; fail closed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post__v3_auth_rotate: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact configured HTTPS origin; no trust in forwarded origin. */
                Origin: string;
                "X-CSRF-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Empty"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Credential"];
                };
            };
            /** @description Invalid JSON/input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid/expired session or assertion */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Capability, CSRF or origin denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource or owner-only route unavailable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description State/version/replay/invariant conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dependency unavailable; fail closed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post__v3_auth_logout: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact configured HTTPS origin; no trust in forwarded origin. */
                Origin: string;
                "X-CSRF-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Empty"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            /** @description Invalid JSON/input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid/expired session or assertion */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Capability, CSRF or origin denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource or owner-only route unavailable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description State/version/replay/invariant conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dependency unavailable; fail closed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "post__v3_auth_revoke-all": {
        parameters: {
            query?: never;
            header: {
                /** @description Exact configured HTTPS origin; no trust in forwarded origin. */
                Origin: string;
                "X-CSRF-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Empty"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            /** @description Invalid JSON/input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid/expired session or assertion */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Capability, CSRF or origin denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource or owner-only route unavailable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description State/version/replay/invariant conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dependency unavailable; fail closed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "post__v3_auth_site-role": {
        parameters: {
            query?: never;
            header: {
                /** @description Exact configured HTTPS origin; no trust in forwarded origin. */
                Origin: string;
                "X-CSRF-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteRole"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            /** @description Invalid JSON/input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid/expired session or assertion */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Capability, CSRF or origin denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource or owner-only route unavailable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description State/version/replay/invariant conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dependency unavailable; fail closed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post__v3_classes: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact configured HTTPS origin; no trust in forwarded origin. */
                Origin: string;
                "X-CSRF-Token": string;
                /** @description Actor-scoped. Same key/payload replays only after current authorization; different payload conflicts. */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClass"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Class"];
                };
            };
            /** @description Invalid JSON/input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid/expired session or assertion */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Capability, CSRF or origin denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource or owner-only route unavailable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description State/version/replay/invariant conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dependency unavailable; fail closed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get__v3_classes_class_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                class_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Class"];
                };
            };
            /** @description Invalid JSON/input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid/expired session or assertion */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Capability, CSRF or origin denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource or owner-only route unavailable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description State/version/replay/invariant conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dependency unavailable; fail closed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patch__v3_classes_class_id: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact configured HTTPS origin; no trust in forwarded origin. */
                Origin: string;
                "X-CSRF-Token": string;
                /** @description Actor-scoped. Same key/payload replays only after current authorization; different payload conflicts. */
                "Idempotency-Key": string;
            };
            path: {
                class_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditClass"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Class"];
                };
            };
            /** @description Invalid JSON/input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid/expired session or assertion */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Capability, CSRF or origin denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource or owner-only route unavailable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description State/version/replay/invariant conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dependency unavailable; fail closed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post__v3_classes_class_id_publish: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact configured HTTPS origin; no trust in forwarded origin. */
                Origin: string;
                "X-CSRF-Token": string;
                /** @description Actor-scoped. Same key/payload replays only after current authorization; different payload conflicts. */
                "Idempotency-Key": string;
            };
            path: {
                class_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Version"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Class"];
                };
            };
            /** @description Invalid JSON/input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid/expired session or assertion */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Capability, CSRF or origin denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource or owner-only route unavailable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description State/version/replay/invariant conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dependency unavailable; fail closed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post__v3_classes_class_id_archive: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact configured HTTPS origin; no trust in forwarded origin. */
                Origin: string;
                "X-CSRF-Token": string;
                /** @description Actor-scoped. Same key/payload replays only after current authorization; different payload conflicts. */
                "Idempotency-Key": string;
            };
            path: {
                class_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Version"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Class"];
                };
            };
            /** @description Invalid JSON/input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid/expired session or assertion */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Capability, CSRF or origin denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource or owner-only route unavailable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description State/version/replay/invariant conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dependency unavailable; fail closed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post__v3_classes_class_id_close: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact configured HTTPS origin; no trust in forwarded origin. */
                Origin: string;
                "X-CSRF-Token": string;
                /** @description Actor-scoped. Same key/payload replays only after current authorization; different payload conflicts. */
                "Idempotency-Key": string;
            };
            path: {
                class_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Version"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Class"];
                };
            };
            /** @description Invalid JSON/input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid/expired session or assertion */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Capability, CSRF or origin denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource or owner-only route unavailable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description State/version/replay/invariant conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dependency unavailable; fail closed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post__v3_classes_class_id_reopen: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact configured HTTPS origin; no trust in forwarded origin. */
                Origin: string;
                "X-CSRF-Token": string;
                /** @description Actor-scoped. Same key/payload replays only after current authorization; different payload conflicts. */
                "Idempotency-Key": string;
            };
            path: {
                class_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Version"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Class"];
                };
            };
            /** @description Invalid JSON/input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid/expired session or assertion */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Capability, CSRF or origin denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource or owner-only route unavailable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description State/version/replay/invariant conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dependency unavailable; fail closed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post__v3_classes_class_id_participants: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact configured HTTPS origin; no trust in forwarded origin. */
                Origin: string;
                "X-CSRF-Token": string;
                /** @description Actor-scoped. Same key/payload replays only after current authorization; different payload conflicts. */
                "Idempotency-Key": string;
            };
            path: {
                class_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Participant"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Participation"];
                };
            };
            /** @description Invalid JSON/input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid/expired session or assertion */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Capability, CSRF or origin denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource or owner-only route unavailable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description State/version/replay/invariant conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dependency unavailable; fail closed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post__v3_classes_class_id_participants_user_id_end: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact configured HTTPS origin; no trust in forwarded origin. */
                Origin: string;
                "X-CSRF-Token": string;
                /** @description Actor-scoped. Same key/payload replays only after current authorization; different payload conflicts. */
                "Idempotency-Key": string;
            };
            path: {
                class_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Empty"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Participation"];
                };
            };
            /** @description Invalid JSON/input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid/expired session or assertion */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Capability, CSRF or origin denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource or owner-only route unavailable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description State/version/replay/invariant conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dependency unavailable; fail closed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post__v3_classes_class_id_participants_user_id_suspend: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact configured HTTPS origin; no trust in forwarded origin. */
                Origin: string;
                "X-CSRF-Token": string;
                /** @description Actor-scoped. Same key/payload replays only after current authorization; different payload conflicts. */
                "Idempotency-Key": string;
            };
            path: {
                class_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Empty"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Participation"];
                };
            };
            /** @description Invalid JSON/input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid/expired session or assertion */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Capability, CSRF or origin denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource or owner-only route unavailable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description State/version/replay/invariant conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dependency unavailable; fail closed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post__v3_classes_class_id_participants_user_id_reactivate: {
        parameters: {
            query?: never;
            header: {
                /** @description Exact configured HTTPS origin; no trust in forwarded origin. */
                Origin: string;
                "X-CSRF-Token": string;
                /** @description Actor-scoped. Same key/payload replays only after current authorization; different payload conflicts. */
                "Idempotency-Key": string;
            };
            path: {
                class_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Empty"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Participation"];
                };
            };
            /** @description Invalid JSON/input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid/expired session or assertion */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Capability, CSRF or origin denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource or owner-only route unavailable */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description State/version/replay/invariant conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dependency unavailable; fail closed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
